basePath: /
definitions:
  api_objects.Building:
    properties:
      campus:
        description: GPS        string   `json:"gps"`
        type: string
      id:
        type: integer
      name:
        type: string
      updateDate:
        type: string
    type: object
  api_objects.BuildingRequest:
    properties:
      campus:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  api_objects.CartItem:
    properties:
      amount:
        type: integer
      amountSelected:
        type: integer
      available:
        type: integer
      buildingName:
        type: string
      id:
        type: integer
      name:
        type: string
      roomName:
        type: string
      shelfId:
        type: string
    type: object
  api_objects.CartRequest:
    properties:
      id:
        type: integer
      numSelected:
        type: integer
    required:
    - id
    - numSelected
    type: object
  api_objects.ColumnElementRequest:
    properties:
      elements:
        items:
          $ref: '#/definitions/api_objects.ShelfElementRequest'
        type: array
      id:
        type: string
    required:
    - elements
    - id
    type: object
  api_objects.Columns:
    properties:
      elements:
        items:
          $ref: '#/definitions/api_objects.Element'
        type: array
      id:
        type: string
    type: object
  api_objects.Element:
    properties:
      id:
        type: string
      type:
        type: string
    type: object
  api_objects.InventoryItemRequest:
    properties:
      amount:
        type: integer
      isConsumable:
        type: boolean
      name:
        type: string
      note:
        type: string
      organisation:
        type: string
      shelfUnitId:
        type: string
    required:
    - amount
    - isConsumable
    - name
    - note
    - shelfUnitId
    type: object
  api_objects.InventoryItemWithShelf:
    properties:
      amount:
        type: integer
      available:
        type: integer
      buildingName:
        type: string
      id:
        type: integer
      name:
        type: string
      roomName:
        type: string
      shelf:
        $ref: '#/definitions/api_objects.Shelves'
      shelfId:
        type: string
    type: object
  api_objects.InventorySorted:
    properties:
      amount:
        type: integer
      available:
        type: integer
      buildingName:
        type: string
      id:
        type: integer
      name:
        type: string
      roomName:
        type: string
    type: object
  api_objects.Room:
    properties:
      buildingName:
        type: string
      floor:
        type: string
      id:
        type: integer
      name:
        type: string
      number:
        type: string
      updateDate:
        type: string
    type: object
  api_objects.RoomRequest:
    properties:
      building:
        type: integer
      floor:
        type: string
      name:
        type: string
      number:
        type: string
    required:
    - building
    - floor
    - number
    type: object
  api_objects.ShelfElementRequest:
    properties:
      id:
        type: string
      type:
        type: string
    required:
    - id
    - type
    type: object
  api_objects.ShelfRequest:
    properties:
      buildingId:
        type: integer
      columns:
        items:
          $ref: '#/definitions/api_objects.ColumnElementRequest'
        type: array
      id:
        type: string
      name:
        type: string
      ownedBy:
        type: string
      roomId:
        type: integer
    required:
    - buildingId
    - columns
    - id
    - name
    - ownedBy
    - roomId
    type: object
  api_objects.ShelfSorted:
    properties:
      buildingName:
        type: string
      id:
        type: string
      name:
        type: string
      roomName:
        type: string
    type: object
  api_objects.Shelves:
    properties:
      buildingName:
        type: string
      columns:
        items:
          $ref: '#/definitions/api_objects.Columns'
        type: array
      id:
        type: string
      name:
        type: string
      roomName:
        type: string
    type: object
  db.Building:
    properties:
      campus:
        type: string
      gps:
        type: string
      id:
        type: integer
      name:
        type: string
      update_date:
        type: string
    type: object
  db.Column:
    properties:
      id:
        type: string
      shelf:
        $ref: '#/definitions/db.Shelf'
      shelf_id:
        type: string
      shelf_units:
        items:
          $ref: '#/definitions/db.ShelfUnit'
        type: array
    type: object
  db.Inventory:
    properties:
      amount:
        type: integer
      id:
        type: integer
      item:
        $ref: '#/definitions/db.Item'
      item_id:
        type: integer
      note:
        type: string
      request_item:
        items:
          $ref: '#/definitions/db.RequestItems'
        type: array
      shelf_unit:
        $ref: '#/definitions/db.ShelfUnit'
      shelf_unit_id:
        type: string
      update_date:
        type: string
    type: object
  db.Item:
    properties:
      id:
        type: integer
      is_consumable:
        description: |-
          Description  string   `json:"description" pg:"description"`
          Category     string   `json:"category" pg:"category"`
        type: boolean
      name:
        type: string
    type: object
  db.Organisation:
    properties:
      name:
        type: string
    type: object
  db.Request:
    properties:
      end_date:
        type: string
      id:
        type: integer
      note:
        type: string
      start_date:
        type: string
      status:
        type: string
      user:
        $ref: '#/definitions/db.User'
      user_id:
        type: integer
    type: object
  db.RequestItems:
    properties:
      amount:
        type: integer
      id:
        type: integer
      inventory:
        $ref: '#/definitions/db.Inventory'
      inventory_id:
        type: integer
      request:
        $ref: '#/definitions/db.Request'
      request_id:
        type: integer
    type: object
  db.Room:
    properties:
      building:
        $ref: '#/definitions/db.Building'
      building_id:
        type: integer
      floor:
        type: string
      id:
        type: integer
      name:
        type: string
      number:
        type: string
      update_date:
        type: string
    type: object
  db.Shelf:
    properties:
      columns:
        items:
          $ref: '#/definitions/db.Column'
        type: array
      id:
        type: string
      name:
        type: string
      organisation:
        $ref: '#/definitions/db.Organisation'
      owned_by:
        type: string
      room:
        $ref: '#/definitions/db.Room'
      room_id:
        type: integer
      update_date:
        type: string
    type: object
  db.ShelfUnit:
    properties:
      column:
        $ref: '#/definitions/db.Column'
      column_id:
        type: string
      description:
        type: string
      id:
        type: string
      position_in_column:
        description: to change the order of the units in the column later
        type: integer
      type:
        description: 0 is small, 1 is big
        type: integer
    type: object
  db.ShoppingCart:
    properties:
      id:
        type: integer
      shopping_cart_items:
        items:
          $ref: '#/definitions/db.ShoppingCartItem'
        type: array
      user_id:
        type: integer
    type: object
  db.ShoppingCartItem:
    properties:
      amount:
        type: integer
      id:
        type: integer
      inventory:
        $ref: '#/definitions/db.Inventory'
      inventory_id:
        type: integer
      shopping_cart:
        $ref: '#/definitions/db.ShoppingCart'
      shopping_cart_id:
        type: integer
    type: object
  db.User:
    properties:
      access_token:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      issuer:
        type: string
      last_login:
        type: string
      name:
        type: string
      refresh_token:
        type: string
      subject:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@lagertool.com
    name: API Support
  description: Backend API for inventory management system tracking items, locations,
    and loans
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Lagertool Inventory API
  version: "1.0"
paths:
  /add_item_to_cart:
    post:
      consumes:
      - application/json
      description: Add an item to the shopping cart
      parameters:
      - description: Cart item object
        in: body
        name: cart_item
        required: true
        schema:
          $ref: '#/definitions/api_objects.CartRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.ShoppingCartItem'
      summary: Add an item to the shopping cart
      tags:
      - shopping_cart
  /buildings_sorted:
    get:
      description: Get all buildings sorted by update date
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_objects.Building'
            type: array
      summary: Get all buildings sorted by update date
      tags:
      - buildings
  /create_building:
    post:
      consumes:
      - application/json
      description: Create a new building
      parameters:
      - description: Building object
        in: body
        name: building
        required: true
        schema:
          $ref: '#/definitions/api_objects.BuildingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.Building'
      summary: Create a new building
      tags:
      - buildings
  /create_item:
    post:
      consumes:
      - application/json
      description: Create a new inventory item
      parameters:
      - description: Inventory item object
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/api_objects.InventoryItemRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.Inventory'
      summary: Create a new inventory item
      tags:
      - items
  /create_room:
    post:
      consumes:
      - application/json
      description: Create a new room
      parameters:
      - description: Room object
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/api_objects.RoomRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.Room'
      summary: Create a new room
      tags:
      - rooms
  /create_shelf:
    post:
      consumes:
      - application/json
      description: Create a new shelf
      parameters:
      - description: Shelf object
        in: body
        name: shelf
        required: true
        schema:
          $ref: '#/definitions/api_objects.ShelfRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/db.Shelf'
      summary: Create a new shelf
      tags:
      - shelves
  /inventory_sorted:
    get:
      description: Get all inventory items sorted by update date
      parameters:
      - description: Start date in format 2006-01-02
        in: query
        name: start
        required: true
        type: string
      - description: End date in format 2006-01-02
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_objects.InventorySorted'
            type: array
      summary: Get all inventory items sorted by update date
      tags:
      - items
  /item:
    get:
      description: Get a specific item
      parameters:
      - description: Organisation name
        in: query
        name: organisation
        required: true
        type: string
      - description: Inventory Item ID
        in: query
        name: id
        required: true
        type: integer
      - description: Start date in format 2006-01-02
        in: query
        name: start
        required: true
        type: string
      - description: End date in format 2006-01-02
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_objects.InventoryItemWithShelf'
      summary: Get a specific item
      tags:
      - items
  /organisations:
    get:
      description: Get all organisations
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Organisation'
            type: array
      summary: Get all organisations
      tags:
      - organisations
  /rooms_sorted:
    get:
      description: Get all rooms sorted by update date
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_objects.Room'
            type: array
      summary: Get all rooms sorted by update date
      tags:
      - rooms
  /shelves:
    get:
      description: Get all shelves
      parameters:
      - description: Organisation name
        in: query
        name: organisation
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_objects.Shelves'
            type: array
      summary: Get all shelves
      tags:
      - shelves
  /shelves_sorted:
    get:
      description: Get all shelves sorted by update date
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api_objects.ShelfSorted'
            type: array
      summary: Get all shelves sorted by update date
      tags:
      - shelves
  /shopping_cart:
    get:
      description: Get a user's shopping cart
      parameters:
      - description: User ID
        in: query
        name: userID
        required: true
        type: integer
      - description: Start date in format 2006-01-02
        in: query
        name: start
        required: true
        type: string
      - description: End date in format 2006-01-02
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/api_objects.CartItem'
              type: array
            type: object
      summary: Get a user's shopping cart
      tags:
      - shopping_cart
schemes:
- http
swagger: "2.0"
